python -m venv venv
venv\Scripts\activate
pip install numpy matplotlib tensorflow scikit-learn
pip install torch torchvision --index-url https://download.pytorch.org/whl/cpu
pip install notebook
python -m notebook

In [28]:
import numpy as np

In [29]:
p1 = np.array([1, -1, 1, -1])
p2 = np.array([-1, 1, -1, 1])
p3 = np.array([1, 1, -1, -1])
p4 = np.array([-1, -1, 1, 1])

patterns = [p1, p2, p3, p4]

print("Stored Patterns:")
for i, p in enumerate(patterns):
    print(f"P{i+1}: {p}")

Stored Patterns:
P1: [ 1 -1  1 -1]
P2: [-1  1 -1  1]
P3: [ 1  1 -1 -1]
P4: [-1 -1  1  1]


In [30]:
size = len(p1)
W = np.zeros((size, size))

for p in patterns:
    W += np.outer(p, p)

# Remove self-connections
np.fill_diagonal(W, 0)

print("\nWeight Matrix:\n", W)


Weight Matrix:
 [[ 0.  0.  0. -4.]
 [ 0.  0. -4.  0.]
 [ 0. -4.  0.  0.]
 [-4.  0.  0.  0.]]


In [31]:
noisy_input = np.array([1, -1, -1, -1])

print("\nNoisy Input:")
print(noisy_input)


Noisy Input:
[ 1 -1 -1 -1]


In [32]:
def recall(x, W, steps=5):
    x = x.copy()
    for _ in range(steps):
        for i in range(len(x)):
            net = np.dot(W[i], x)
            x[i] = 1 if net >= 0 else -1
    return x

In [33]:
recalled = recall(noisy_input, W)

print("\nRecalled Pattern:")
print(recalled)


Recalled Pattern:
[ 1  1 -1 -1]
